In this section, We will be dealing with exceptions under Python
